In [9]:
import boto3 # Python integration with AWS.
import pandas as pd # Read csv.
from io import StringIO # Read csv on AWS.

In [10]:
# Variables for data on AWS S3.
s3 = boto3.resource('s3')
bucket = s3.Bucket('xetra-1234')

In [11]:
# List of filtered CSVs.
# Two filters.
bucket_obj1 = bucket.objects.filter(Prefix='2022-02-15/')
bucket_obj2 = bucket.objects.filter(Prefix='2022-02-16/')
objects = [obj for obj in bucket_obj1] + [obj for obj in bucket_obj2]

In [12]:
# Print list.
objects

[s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-15/2022-02-15_BINS_XETR23.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR00.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR01.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR02.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR03.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR04.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR05.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR06.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR07.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR08.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR09.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR10.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR11.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR12.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR13.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR14.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR15.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR16.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR17.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR18.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR19.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR20.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR21.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR22.csv'),
 s3.ObjectSummary(bucket_name='xetra-1234', key='2022-02-16/2022-02-16_BINS_XETR23.csv')]

In [27]:
# Initial data frame.
csv_obj_init = bucket.Object(key=objects[0].key).get().get('Body').read().decode('utf-8')
data = StringIO(csv_obj_init)
df_init = pd.read_csv(data, delimiter=',')

In [28]:
# Columns of initial data frame.
df_init.columns

Index(['ISIN', 'Mnemonic', 'SecurityDesc', 'SecurityType', 'Currency',
       'SecurityID', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice',
       'EndPrice', 'TradedVolume', 'NumberOfTrades'],
      dtype='object')

In [29]:
# Read csv.

# Initialize single data frame for all dfs.
df_all = pd.DataFrame(columns=df_init.columns)

# Loop for multiple csvs.
for obj in objects:
    csv_obj = bucket.Object(key=obj.key).get().get('Body').read().decode('utf-8')
    # Read csvs with StringIO (needed for AWS) and Pandas
    data = StringIO(csv_obj)
    df = pd.read_csv(data, delimiter=',')
    # Single data frame for all dfs.
    df_all = df_all.append(df, ignore_index=True)

C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)

C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)
C:\Users\gedim\AppData\Local\Temp\ipykernel_14296\1253865853.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = df_all.append(df, ignore_index=True)

In [30]:
df_all

,ISIN,Mnemonic,SecurityDesc,SecurityType,Currency,SecurityID,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume,NumberOfTrades
0,AT0000A0E9W5,SANT,S+T AG O.N.,Common stock,EUR,2504159,2022-02-15,08:00,15.720,15.720,15.700,15.700,1991,3
1,DE000A0DJ6J9,S92,SMA SOLAR TECHNOL.AG,Common stock,EUR,2504287,2022-02-15,08:00,29.600,29.620,29.600,29.620,575,4
2,DE000A0D6554,NDX1,NORDEX SE O.N.,Common stock,EUR,2504290,2022-02-15,08:00,12.850,12.850,12.790,12.790,5318,16
3,DE000A0D9PT0,MTX,MTU AERO ENGINES NA O.N.,Common stock,EUR,2504297,2022-02-15,08:00,193.050,193.050,192.150,192.150,1410,11
4,DE000A0HN5C6,DWNI,DEUTSCHE WOHNEN SE INH,Common stock,EUR,2504314,2022-02-15,08:00,36.410,36.410,36.410,36.410,32,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222237,DE0006231004,IFX,INFINEON TECH.AG NA O.N.,Common stock,EUR,2505024,2022-02-16,16:43,33.195,33.195,33.195,33.195,3000,1
222238,DE0008232125,LHA,LUFTHANSA AG VNA O.N.,Common stock,EUR,2505130,2022-02-16,16:43,7.807,7.807,7.807,7.807,500,2
222239,DE0008402215,HNR1,HANNOVER RUECK SE NA O.N.,Common stock,EUR,2505132,2022-02-16,16:43,176.050,176.050,176.050,176.050,273,2
222240,DE0006231004,IFX,INFINEON TECH.AG NA O.N.,Common stock,EUR,2505024,2022-02-16,16:44,33.195,33.195,33.195,33.195,2000,2
222241,DE0007664039,VOW3,VOLKSWAGEN AG VZO O.N.,Common stock,EUR,2505114,2022-02-16,16:44,186.020,186.020,186.020,186.020,75,2

In [31]:
# DF with filtered columns.
columns = ['ISIN', 'Date', 'Time', 'StartPrice', 'MaxPrice', 'MinPrice', 'EndPrice', 'TradedVolume']
df_all = df_all.loc[:, columns]

In [32]:
df_all

,ISIN,Date,Time,StartPrice,MaxPrice,MinPrice,EndPrice,TradedVolume
0,AT0000A0E9W5,2022-02-15,08:00,15.720,15.720,15.700,15.700,1991
1,DE000A0DJ6J9,2022-02-15,08:00,29.600,29.620,29.600,29.620,575
2,DE000A0D6554,2022-02-15,08:00,12.850,12.850,12.790,12.790,5318
3,DE000A0D9PT0,2022-02-15,08:00,193.050,193.050,192.150,192.150,1410
4,DE000A0HN5C6,2022-02-15,08:00,36.410,36.410,36.410,36.410,32
...,...,...,...,...,...,...,...,...
222237,DE0006231004,2022-02-16,16:43,33.195,33.195,33.195,33.195,3000
222238,DE0008232125,2022-02-16,16:43,7.807,7.807,7.807,7.807,500
222239,DE0008402215,2022-02-16,16:43,176.050,176.050,176.050,176.050,273
222240,DE0006231004,2022-02-16,16:44,33.195,33.195,33.195,33.195,2000
222241,DE0007664039,2022-02-16,16:44,186.020,186.020,186.020,186.020,75

In [33]:
# Filter out empty lines.
df_all.dropna(inplace=True)

In [34]:
# Check number of entries after filtering.
df_all.shape

(222242, 8)